[workspace]
members = [
    "components/api",
    "components/db",
    "components/cron",
    "components/ml",
]

default-members = [
    "components/api",
    "components/db",
    "components/cron",
    "components/ml",
]


