type NewsFeedBuildMetadata {
	updatedAt: Int!
	totalCount: Int!
}

type NewsFeedStatus {
	completedAt: Int
}

type NewsFeedUrl {
	urlSlug: String!
	urlId: Int!
	urlScore: Int!
	numReferences: Int!
	firstReferencedByUsername: String!
	createdAt: Int!
	updatedAt: Int!
	title: String
	description: String
	expandedUrlParsed: String!
	expandedUrlHost: String!
	displayUrl: String
	previewImageThumbnailUrl: String
	previewImageUrl: String
}

type NewsFeedUrlReference {
	urlId: Int!
	postUri: String!
	postText: String!
	postCreatedAtStr: String!
	authorHandle: String!
	repostedByHandles: [String!]!
}

type Query {
	newsFeedStatus: NewsFeedStatus
	newsFeedUrls: [NewsFeedUrl!]!
	newsFeedUrl(urlSlug: String!): NewsFeedUrl!
	newsFeedUrlReferences(urlSlug: String!): [NewsFeedUrlReference!]!
	sitemapNewsFeedUrlSlugs(month: Int!, year: Int!): [String!]!
	newsFeedUrlSlugs(limit: Int, offset: Int): [String!]!
	newsFeedBuildMetadata: NewsFeedBuildMetadata!
}

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
schema {
	query: Query
}
