name: news service api

defaults:
  run:
    working-directory: news_service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: SQLX_OFFLINE=true cargo build --release --verbose --bin cron
    # - name: Run tests
    #   run: SQLX_OFFLINE=true cargo test --verbose
# TODO add cargo clippy + git precommit hook?
# Use postgres or in memory for unit tests
