name: web

on:
  create:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # TODO Run tests before deploying, add git hash to tag
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./web
          push: true
          tags: |
              ${{ secrets.DOCKER_HUB_USERNAME }}/web:${{ steps.vars.outputs.tag }}
              ${{ secrets.DOCKER_HUB_USERNAME }}/web:latest          
