name: api_tag


# Deploy docker image on a new tag push
on:
  create:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./news_service
          push: true
          build-args: SERVICE_NAME=api
          tags: |
            climateactioncollective/news_api:${{ github.ref_name }}
            climateactioncollective/news_api:latest
