name: news_service api

# run build steps for all pushes
# on:
#   push:
#     branches:
#       - 'main'
# TODO only deploy docker images on a new tag
on:
  create:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./news_service
          push: true
          build-args: SERVICE_NAME=api
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/news_api:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/news_api:latest
